--Creating table AUTHOR
CREATE TABLE AUTHOR
(
    Aut_Id   INT IDENTITY PRIMARY KEY,
    Aut_Name VARCHAR(255) NOT NULL,
    Aut_Bio  varchar(max)
);

--Creating table PUBLISHER
CREATE TABLE PUBLISHER
(
    Pub_Id    INT IDENTITY PRIMARY KEY,
    Pub_Name  VARCHAR(255) NOT NULL,
    Pub_Phone VARCHAR(255) NOT NULL
);

--Creating table BOOK_LANGUAGE
CREATE TABLE BOOK_LANGUAGE
(
    BoL_Id   INT IDENTITY PRIMARY KEY,
    BoL_Name VARCHAR(255) NOT NULL
);

--Creating table BOOK
CREATE TABLE BOOK
(
    Boo_ISBN        VARCHAR(13) PRIMARY KEY,
    Pub_Id          INT            NOT NULL,
    BoL_Id          INT            NOT NULL,
    Boo_Title       VARCHAR(255)   NOT NULL,
    Boo_Description varchar(max),
    Boo_Price       DECIMAL(10, 2) NOT NULL,
    Boo_Pub_Date    DATE,
    Boo_Img_url     varchar(max),
    Boo_Featured    BIT,
    Boo_QOH         INT            NOT NULL,
    FOREIGN KEY (Pub_Id) REFERENCES PUBLISHER (Pub_Id),
    FOREIGN KEY (BoL_Id) REFERENCES BOOK_LANGUAGE (BoL_Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

--Creating table BOOK_AUTHOR
CREATE TABLE BOOK_AUTHOR
(
    Boo_ISBN VARCHAR(13),
    Aut_Id   INT,
    CONSTRAINT boo_aut_id PRIMARY KEY (Boo_ISBN, Aut_Id),
    FOREIGN KEY (Boo_ISBN) REFERENCES BOOK (Boo_ISBN),
    FOREIGN KEY (Aut_Id) REFERENCES AUTHOR (Aut_Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

--Creating table ROLE
CREATE TABLE ROLE
(
    Rol_Id   INT IDENTITY PRIMARY KEY,
    Rol_Name VARCHAR(255) NOT NULL
);

--Creating table GENRE
CREATE TABLE GENRE
(
    Gen_Id   INT IDENTITY PRIMARY KEY,
    Gen_Name VARCHAR(255) NOT NULL
);

--Creating table BOOK_GENRE
CREATE TABLE BOOK_GENRE
(
    Boo_ISBN VARCHAR(13),
    Gen_Id   INT,
    CONSTRAINT boo_gen_id PRIMARY KEY (Boo_ISBN, Gen_Id),
    FOREIGN KEY (Boo_ISBN) REFERENCES BOOK (Boo_ISBN),
    FOREIGN KEY (Gen_Id) REFERENCES GENRE (Gen_Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

--Creating table SHIPPING_METHOD
CREATE TABLE SHIPPING_METHOD
(
    ShM_Id    INT IDENTITY PRIMARY KEY,
    ShM_Name  VARCHAR(255)   NOT NULL,
    ShM_Price DECIMAL(10, 2) NOT NULL
);

--Creating table CUSTOMER
CREATE TABLE CUSTOMER
(
    Cus_Id        INT IDENTITY PRIMARY KEY,
    Cus_FirstName VARCHAR(255) NOT NULL,
    Cus_LastName  VARCHAR(255) NOT NULL,
    Cus_Email     VARCHAR(255) NOT NULL,
    Cus_Phone     VARCHAR(255) NOT NULL,
    Rol_id        INT          NOT NULL,
    Cus_Pass      VARCHAR(255),
    FOREIGN KEY (Rol_id) REFERENCES ROLE (Rol_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

--Creating table ORDER_STATUS
CREATE TABLE ORDER_STATUS
(
    OrS_Id   INT IDENTITY PRIMARY KEY,
    OrS_Name VARCHAR(255) NOT NULL
);

--Creating table COUNTRY
CREATE TABLE COUNTRY
(
    Cou_Id   INT IDENTITY PRIMARY KEY,
    Cou_Name VARCHAR(255) NOT NULL
);

--Creating table ADDRESS
CREATE TABLE ADDRESS
(
    Add_Id          INT IDENTITY PRIMARY KEY,
    Add_Street_Nr   INT          NOT NULL,
    Add_Street_Name VARCHAR(255) NOT NULL,
    Add_City        VARCHAR(255) NOT NULL,
    Cou_Id          INT          NOT NULL,
    FOREIGN KEY (Cou_Id) REFERENCES COUNTRY (Cou_Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

--Creating table ADDRESS_STATUS
CREATE TABLE ADDRESS_STATUS
(
    AdS_Id   INT IDENTITY PRIMARY KEY,
    AdS_Name VARCHAR(255) NOT NULL
);

--Creating table CUSTOMER_ADDRESS
CREATE TABLE CUSTOMER_ADDRESS
(
    Cus_Id INT,
    Add_Id INT,
    AdS_Id INT NOT NULL,
    CONSTRAINT cus_add_id PRIMARY KEY (Cus_Id, Add_Id),
    FOREIGN KEY (Cus_Id) REFERENCES CUSTOMER (Cus_Id),
    FOREIGN KEY (Add_Id) REFERENCES ADDRESS (Add_Id),
    FOREIGN KEY (AdS_Id) REFERENCES ADDRESS_STATUS (AdS_Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

--Creating table ORDER
CREATE TABLE CUS_ORDER
(
    Ord_Id   INT IDENTITY PRIMARY KEY,
    Cus_Id   INT NOT NULL,
    ShM_Id   INT NOT NULL,
    Ord_Date DATE,
    Add_Id   INT NOT NULL,
    FOREIGN KEY (Cus_Id) REFERENCES CUSTOMER (Cus_Id),
    FOREIGN KEY (ShM_Id) REFERENCES SHIPPING_METHOD (ShM_Id),
    FOREIGN KEY (Add_Id) REFERENCES ADDRESS (Add_Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

--Creating table ORDER_LINE
CREATE TABLE ORDER_LINE
(
    Boo_ISBN     VARCHAR(13),
    Ord_Id       INT,
    OrL_Quantity INT NOT NULL,
    CONSTRAINT ord_lin_id PRIMARY KEY (Boo_ISBN, Ord_Id),
    FOREIGN KEY (Boo_ISBN) REFERENCES BOOK (Boo_ISBN),
    FOREIGN KEY (Ord_Id) REFERENCES CUS_ORDER (Ord_Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

--Creating table ORDER_HISTORY
CREATE TABLE ORDER_HISTORY
(
    OrS_Id          INT,
    Ord_Id          INT,
    OrH_Description varchar(max),
    OrH_Date        DATE,
    CONSTRAINT ord_his_id PRIMARY KEY (OrS_Id, Ord_Id),
    FOREIGN KEY (OrS_Id) REFERENCES ORDER_STATUS (OrS_Id),
    FOREIGN KEY (Ord_Id) REFERENCES CUS_ORDER (Ord_Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

--Creating table CART
CREATE TABLE CART
(
    Car_Id INT IDENTITY PRIMARY KEY,
    Cus_Id INT NOT NULL,
    FOREIGN KEY (Cus_Id) REFERENCES CUSTOMER (Cus_Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

--Creating table CART_LINE
CREATE TABLE CART_LINE
(
    Boo_ISBN VARCHAR(13),
    Car_Id   INT,
    CONSTRAINT car_lin_id PRIMARY KEY (Boo_ISBN, Car_Id),
    FOREIGN KEY (Boo_ISBN) REFERENCES BOOK (Boo_ISBN),
    FOREIGN KEY (Car_Id) REFERENCES CART (Car_Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

--Creating table EMPLOYEE
CREATE TABLE EMPLOYEE
(
    Emp_Id        INT IDENTITY PRIMARY KEY,
    Emp_FirstName VARCHAR(255) NOT NULL,
    Emp_LastName  VARCHAR(255) NOT NULL,
    Rol_Id        INT          NOT NULL,
    FOREIGN KEY (Rol_Id) REFERENCES ROLE (Rol_Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);