INSERT INTO BOOK_LANGUAGE (BoL_Name)
VALUES ('English');

INSERT INTO BOOK_LANGUAGE (BoL_Name)
VALUES ('Spanish');

INSERT INTO BOOK_LANGUAGE (BoL_Name)
VALUES ('French');

INSERT INTO BOOK_LANGUAGE (BoL_Name)
VALUES ('German');

INSERT INTO BOOK_LANGUAGE (BoL_Name)
VALUES ('Italian');
